services:
  web:
    build: .
    ports:
      - "8000:5000"
    container_name: flask_felipe
    develop:
      watch:
        - action: sync
          path: .
          target: /code
  redis:
    image: "redis:alpine"

